related_positions = {
  "GK": [],
  "RB": ["RWB"],
  "CB": [],
  "LB": ["LWB"],
  "RWB": ["RB"],
  "LWB": ["LB"],
  "CDM": ["CM"],
  "CM": ["CDM", "CAM"],
  "CAM": ["CM"],
  "RM": ["RW"],
  "LM": ["LW"],
  "RW": ["RM", "RF"],
  "LW": ["LM", "LF"],
  "CF": ["CAM", "ST"],
  "RF": ["RW"],
  "LF": ["LW"],
  "ST": ["CF"],
}

unrelated_positions = {
  "GK": [],
  "RB": ["CB", "LB", "RM"],
  "CB": ["RB", "LB", "CDM"],
  "LB": ["CB", "RB", "LM"],
  "RWB": ["LWB", "RM", "RW"],
  "LWB": ["RWB", "LM", "LW"],
  "CDM": ["CB", "CAM"],
  "CM": ["RM", "LM"],
  "CAM": ["CDM"],
  "RM": ["RB", "RWB", "CM", "LM", "RF"],
  "LM": ["LB", "LWB", "CM", "RM", "LF"],
  "RW": ["RWB", "LW"],
  "LW": ["LWB", "RW"],
  "CF": ["RF", "LF"],
  "RF": ["CF", "LF", "ST"],
  "LF": ["CF", "RF", "ST"],
  "ST": ["RF", "LF"],
}